name: Compilar APK Ilha Dinamica

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descarregar repositório
      uses: actions/checkout@v4

    - name: Extrair o ficheiro ZIP
      run: unzip -o *.zip || echo "Nenhum ficheiro ZIP encontrado!"

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Encontrar pasta e Compilar APK
      run: |
        echo "A procurar o ficheiro gradlew..."
        GRADLEW_PATH=$(find . -name gradlew | head -n 1)
        
        if [ -z "$GRADLEW_PATH" ]; then
          echo "ERRO: O ficheiro 'gradlew' não existe! O teu ZIP está incompleto ou não foi enviado."
          exit 1
        fi
        
        PASTA=$(dirname "$GRADLEW_PATH")
        echo "A entrar na pasta: $PASTA"
        cd "$PASTA"
        
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Guardar o APK gerado
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: IlhaDinamica-APK
        path: "**/*.apk"
