name: Compilar APK Ilha Dinamica

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descarregar repositório
      uses: actions/checkout@v4

    - name: Extrair o ficheiro ZIP
      run: unzip -o *.zip

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Encontrar pasta e Compilar APK
      run: |
        # Este comando procura automaticamente onde está o ficheiro gradlew
        PASTA=$(dirname $(find . -name gradlew | head -n 1))
        echo "A entrar na pasta do projeto: $PASTA"
        cd "$PASTA"
        
        # Dar permissão e compilar
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Guardar o APK gerado
      uses: actions/upload-artifact@v4
      with:
        name: IlhaDinamica-APK
        # Este comando procura qualquer ficheiro .apk gerado e guarda-o
        path: "**/*.apk"
